//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarTum.Windows.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Clienteconfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static Clienteconfig defaultInstance = ((Clienteconfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Clienteconfig())));
        
        public static Clienteconfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("servidor")]
        public string tipo {
            get {
                return ((string)(this["tipo"]));
            }
            set {
                this["tipo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool primeiro_acesso {
            get {
                return ((bool)(this["primeiro_acesso"]));
            }
            set {
                this["primeiro_acesso"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.122")]
        public string ServidorIP {
            get {
                return ((string)(this["ServidorIP"]));
            }
            set {
                this["ServidorIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1515")]
        public int ServidorPorta {
            get {
                return ((int)(this["ServidorPorta"]));
            }
            set {
                this["ServidorPorta"] = value;
            }
        }
    }
}
